import WAN_LOGO from './assets/WAN.jpg';
import YOUTUBE_LOGO from './assets/youtube.png';

const VIA = [
  {
    id: 1,
    name: 'Nikki Cueno',
    is_available: true,
    is_wl: false,
  },
  {
    id: 2,
    name: 'Justine Judilla',
    is_available: true,
    is_wl: false,
  },
  {
    id: 3,
    name: 'Eunice Nikki Floralde',
    is_available: true,
    is_wl: false,
  },
  {
    id: 4,
    name: 'John Pallan',
    is_available: true,
    is_wl: false,
  },
  {
    id: 5,
    name: 'Diane Agreda',
    is_available: true,
    is_wl: false,
  },
  {
    id: 6,
    name: 'Reisel Ann Cayao',
    is_available: true,
    is_wl: false,
  },
];

const LINEUP = [
  {
    id: 1,
    label: 'Opening Song',
    artist: '',
    album: '',
    lyrics: '',
    chords: '',
    disabled: false,
    is_solemn: true,
  },
  {
    id: 2,
    label: 'Welcome Song',
    artist: '',
    album: '',
    lyrics: '',
    chords: '',
    disabled: false,
    is_solemn: false,
  },
  {
    id: 3,
    label: 'Joyful Song #1',
    artist: '',
    album: '',
    lyrics: '',
    chords: '',
    disabled: false,
    is_solemn: false,
  },
  {
    id: 4,
    label: 'Joyful Song #2',
    artist: '',
    album: '',
    lyrics: '',
    chords: '',
    disabled: false,
    is_solemn: false,
  },
  {
    id: 5,
    label: 'Joyful Song #3',
    artist: '',
    album: '',
    lyrics: '',
    chords: '',
    disabled: false,
    is_solemn: false,
  },
  {
    id: 6,
    label: 'Solemn Song #1',
    artist: '',
    album: '',
    lyrics: '',
    chords: '',
    disabled: false,
    is_solemn: true,
  },
  {
    id: 7,
    label: 'Solemn Song #2',
    artist: '',
    album: '',
    lyrics: '',
    chords: '',
    disabled: false,
    is_solemn: true,
  },
  {
    id: 8,
    label: 'Solemn Song #3',
    artist: '',
    album: '',
    lyrics: '',
    chords: '',
    disabled: false,
    is_solemn: true,
  },
  {
    id: 9,
    label: 'Pastoral Song',
    artist: '',
    album: '',
    lyrics: '',
    chords: '',
    disabled: false,
    is_solemn: true,
  },
  {
    id: 10,
    label: 'Victory Song',
    artist: '',
    album: '',
    lyrics: '',
    chords: '',
    disabled: false,
    is_solemn: false,
  },
  {
    id: 11,
    label: 'Closing Song',
    artist: '',
    album: '',
    lyrics: '',
    chords: '',
    disabled: false,
    is_solemn: true,
  },
];

export { VIA, LINEUP, WAN_LOGO, YOUTUBE_LOGO };
